### PR TITLE
Add restore function to act as detokenize

### PR DESCRIPTION
**Pull request by kennykarnama**
- [x] new feature to restore tokenization based on the given tokenized string performed before
remember this is an effort to match as close as possible

### CODE REVIEW

**Comment by kennykarnama** [comment]
@euskadi31 can you take look at my PR ? thanks 👍

**Comment by euskadi31** [comment]
Hi @kennykarnama,

Thank you very much for your contribution, can you explain to me the case of use of this function?

If you tokenize your string that means you had the original string? why restore?

**Comment by kennykarnama** [comment]
actually i was about to use your tokenizer to filter word by word from chatting message. After i modify the word that doesn't pass the filter, than i would like to restore it to the original string 
the idea is like what is provided in moses nltk python

**Comment by euskadi31** [comment]
@kennykarnama You can do that with the `KeepSeparator` option.

see: https://github.com/euskadi31/go-tokenizer/blob/master/tokenizer_test.go#L29

**Pull request closed without merging**
